vich_uploader:
    db_driver: orm

    mappings:
        contrat:
            uri_prefix: /upload/contrat
            upload_destination: '%kernel.project_dir%/public/upload/contrat'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
